import { useState, Suspense } from "react";
import Head from "next/head";
import Profile from "../components/Profile";
import Navbar from "../components/Navbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dimensional</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container mx-auto z-0">
          <Navbar />
          <Profile />
        </div>
      </main>
    </>
  );
}
